apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: rental-ingress
  labels:
    app: rental-ingress
spec:
  ingressClassName: nginx
  rules:
    - host: rental-service.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: rental-service
                port:
                  number: 8080
    - host: surname-service.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: surname-service
                port:
                  number: 80
